apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o16hr5iqe-python 
  janus-idp.io/tekton: o16hr5iqe-python
  backstage.io/kubernetes-id: o16hr5iqe-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o16hr5iqe-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml