apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o16hr5iqe-python
  janus-idp.io/tekton: o16hr5iqe-python
  backstage.io/kubernetes-id: o16hr5iqe-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o16hr5iqe-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
